[package]
name = "tui-mm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
crossterm = "0.23.0"
lazy_static = "1.4.0"
rand = "0.8.5"
tui = "0.17.0"
